# Generated by Django 3.2 on 2021-04-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstoreapp', '0002_auto_20210407_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
